### PR TITLE
Fix annotations usage

### PR DESCRIPTION
**Pull request by fromanirh**
fix a bug and a misuse of VM annotations about parent template.

### CODE REVIEW

**Comment by ksimon1** [comment]
Code LGTM, i am not sure about functionality, we should wait for @MarSik review

**Comment by MarSik** [comment]
Looks good to me, one question though. What happens when someone uses both annotation and label method?

**Comment by fromanirh** [comment]
> Looks good to me, one question though. What happens when someone uses both annotation and label method?

Good point. Add notes to the README to clarify.

**Pull request merged**
